# Generated by Django 3.2.8 on 2022-01-23 16:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Deskripsi Produk : '),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.FloatField(verbose_name='Harga yang akan di jual : '),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='img/', verbose_name='Poto Terkait Produk : '),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(verbose_name='Harga Asli : '),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Nama Produk : '),
        ),
    ]
