# Generated by Django 3.2.8 on 2022-02-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='disc_amount',
            field=models.IntegerField(default=0),
        ),
    ]
