# Generated by Django 3.2.8 on 2022-02-11 17:19

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_coupon_disc_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=2),
        ),
    ]
