# Generated by Django 3.2.8 on 2022-02-14 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20220214_1329'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingAddress',
        ),
    ]
