# Generated by Django 3.2.8 on 2022-02-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_link',
            field=models.SlugField(default='', max_length=255),
        ),
    ]
